apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuber-todo.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kuber-todo.labels" (dict "root" . "component" "api" "version" .Values.image.tag) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "kuber-todo.name" . }}
    component: api
