{{- if .Values.ingress.enabled }}
{{- $svc := include "kuber-todo.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $svc }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kuber-todo.labels" (dict "root" . "component" "ingress" "version" .Values.image.tag) | nindent 4 }}
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kuber-todo.fullname" . }}-api
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    {{ toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
