apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuber-todo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Soda-xyz/KubernetesToDo'
    targetRevision: main
    path: k8s/helm/kuber-todo
    helm:
      values: |-
        image:
          repository: "<AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_REPOSITORY>"
          tag: "<IMAGE_TAG>"
        ingress:
          host: "todo.example.com"
        mongodb:
          # Use a Kubernetes Secret instead of embedding a plaintext password here.
          # CI should create a Secret named 'kuber-todo-mongodb-root' with key 'root-password'.
          rootPasswordSecretName: kuber-todo-mongodb-root
          rootPasswordKey: root-password
        # If your image registry is private (ECR), provide an imagePullSecret name here
        # or enable node-side ECR credential provider / IRSA so nodes can pull images.
        imagePullSecrets:
          - name: ecr-registry
  destination:
    server: 'https://kubernetes.default.svc'
  namespace: kuber-todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

