apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuber-todo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Soda-xyz/KubernetesToDo"
    targetRevision: main
    path: k8s/helm/kuber-todo
    helm:
      values: |-
        image:
          repository: "984649216408.dkr.ecr.eu-west-1.amazonaws.com/kuber-todo"
          tag: "latest"
        ingress:
          host: "todo.example.com"
        mongodb:
          image:
            repository: "mongo"
            tag: "6.0"
          rootPasswordSecretName: kuber-todo-mongodb-root
          rootPasswordKey: root-password
          persistence:
            storageClass: gp2
            type: emptyDir
        # imagePullSecrets removed — registry is public or managed separately
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kuber-todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
