# Default values for kuber-todo chart
# Edit to match your registry and ingress host

image:
  repository: "<registry>/kuber-todo"
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "todo.example.com"
  # Default to the nginx ingress class for the MVP; override in values or with --set when installing
  className: "nginx"
  annotations: {}
  tls: []

mongodb:
  enabled: true
  replicaCount: 1
  image:
    repository: bitnami/mongodb
    tag: 6.0.12
  rootUsername: root
  rootPassword: ""
  rootPasswordSecretName: ""
  rootPasswordKey: "root-password"
  database: kuber_todo_db
  service:
    port: 27017
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Probes configuration for readiness and liveness
probes:
  api:
    liveness:
      enabled: true
      path: /health
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 3
      timeoutSeconds: 5
    readiness:
      enabled: true
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
      timeoutSeconds: 3
  mongodb:
    liveness:
      enabled: true
      port: 27017
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 5
    readiness:
      enabled: true
      port: 27017
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
