apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-secret-manager
  namespace: kuber-todo
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","create","update","patch","delete"]
