name: Validate OIDC -> IAM -> Kubernetes RBAC
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  validate-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # Use the repository secret created from the deployment guide
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS identity
        run: |
          echo '--- caller identity ---'
          aws sts get-caller-identity

      - name: Describe EKS cluster
        run: aws eks describe-cluster --name final-disco-ladybug --region eu-west-1 --output yaml

      - name: Install kubectl (matching cluster)
        run: |
          set -e
          K8S_VERSION="v1.32.9"
          echo "Downloading kubectl ${K8S_VERSION}"
          curl -fsSLo kubectl "https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig (verbose)
        run: aws eks update-kubeconfig --name final-disco-ladybug --region eu-west-1 --verbose

      - name: kubectl client info & context
        run: |
          kubectl version --client --short || true
          kubectl config view --minify
          kubectl config current-context || true

      - name: Verify RBAC can create secret
        run: kubectl auth can-i create secrets -n kuber-todo
